### ISSUE TITLE
Great Utility - Does not seem to work with Sound Reactive WLed v12.0

### ISSUE THREAD

**Issue by dsssssssss9** [thibmaek/wled-backup#1]
Hi

Works fine on WLED v13.01 on ESP8266 boards

However on Sound Reactive WLED 12.0 although the command runs with no error - no files are created in the current directory

This was run using Linux version of your utility ...

Is this to do with it being an older version than the current or is it due to being sound reactive WLed?

Hope you can shed some light on this

**Comment by thibmaek** [comment]
Hmmm I'm not sure why It wouldn't work. The docs on https://kno.wled.ge say that it should be available:

> Starting from version 0.8.4, WLED implements a powerful JSON API over HTTP. It is accessible using the /json subpage.

Since this just fetches config over the JSON API you can easily test in a browser to see what your Sound Reactive WLED device returns so I can further debug it. Go to `http://<ip-of-your-sound-reactive-wled-device>/json/cfg` in a browser and post its JSON output here or a screenshot of what you see on the page.

PS: Be sure to strip sensitive data from the response of the web page.

<blockquote><div><strong><a href="https://kno.wled.ge/">Welcome to WLED - WLED Project</a></strong></div></blockquote>

**Comment by dsssssssss9** [comment]
Hi 
Thanks so much for getting back to me ....

This is what i get - when i run your command

> {"error":"Not implemented"}



HOWEVER if i change this to ,,,
http//Myip/json

I get the following....

> {"state":{"on":true,"bri":128,"transition":7,"ps":-1,"pl":-1,"ccnf":{"min":1,"max":5,"time":12},"nl":{"on":false,"dur":60,"fade":true,"mode":1,"tbri":0,"rem":-1},"udpn":{"send":false,"recv":true},"lor":0,"mainseg":0,"seg":[{"id":0,"start":0,"stop":30,"len":30,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":true,"rev":false,"mi":false}]},"info":{"ver":"0.12.0","vid":2104020,"leds":{"count":30,"rgbw":false,"wv":false,"pin":[2],"pwr":477,"fps":2,"maxpwr":850,"maxseg":12,"seglock":false},"str":false,"name":"WLED-SoundReactive","udpport":21324,"live":false,"lm":"","lip":"","ws":0,"fxcount":133,"palcount":56,"wifi":{"bssid":"FF:FF:FF:FF:FF:FF","rssi":31,"signal":100,"channel":1},"fs":{"u":32,"t":1024,"pmt":0},"ndc":-1,"arch":"esp8266","core":"2_7_4_7","lwip":1,"freeheap":22656,"uptime":418,"opt":9,"brand":"WLED","product":"FOSS","mac":"ac0bfbd67b93"},"effects":[
"Solid","Blink","Breathe","Wipe","Wipe Random","Random Colors","Sweep","Dynamic","Colorloop","Rainbow",
"Scan","Scan Dual","Fade","Theater","Theater Rainbow","Running","Saw","Twinkle","Dissolve","Dissolve Rnd",
"Sparkle","Sparkle Dark","Sparkle+","Strobe","Strobe Rainbow","Strobe Mega","Blink Rainbow","Android","Chase","Chase Random",
"Chase Rainbow","Chase Flash","Chase Flash Rnd","Rainbow Runner","Colorful","Traffic Light","Sweep Random","Running 2","Aurora","Stream",
"Scanner","Lighthouse","Fireworks","Rain","Tetrix","Fire Flicker","Gradient","Loading","Police","Police All",
"Two Dots","Two Areas","Circus","Halloween","Tri Chase","Tri Wipe","Tri Fade","Lightning","ICU","Multi Comet",
"Scanner Dual","Stream 2","Oscillate","Pride 2015","Juggle","Palette","Fire 2012","Colorwaves","Bpm","Fill Noise",
"Noise 1","Noise 2","Noise 3","Noise 4","Colortwinkles","Lake","Meteor","Meteor Smooth","Railway","Ripple",
"Twinklefox","Twinklecat","Halloween Eyes","Solid Pattern","Solid Pattern Tri","Spots","Spots Fade","Glitter","Candle","Fireworks Starburst",
"Fireworks 1D","Bouncing Balls","Sinelon","Sinelon Dual","Sinelon Rainbow","Popcorn","Drip","Plasma","Percent","Ripple Rainbow",
"Heartbeat","Pacifica","Candle Multi","Solid Glitter","Sunrise","Phased","Phased Noise","Twinkleup","Noise Pal","Sine",
"Flow","Chunchun","Dancing Shadows","Washing Machine","Candy Cane","Blends","TV Simulator","Dynamic Smooth","* Pixels","* Pixelwave",
"* Juggles","* Matripix","* Gravimeter","* Plasmoid","* Puddles","* Midnoise","* Noisemeter","* Noisefire","* Puddlepeak","* Ripplepeak",
"* Waterfall","* Gravcenter","* Gravcentric"
],"palettes":[
"Default","* Random Cycle","* Color 1","* Colors 1&2","* Color Gradient","* Colors Only","Party","Cloud","Lava","Ocean",
"Forest","Rainbow","Rainbow Bands","Sunset","Rivendell","Breeze","Red & Blue","Yellowout","Analogous","Splash",
"Pastel","Sunset 2","Beech","Vintage","Departure","Landscape","Beach","Sherbet","Hult","Hult 64",
"Drywet","Jul","Grintage","Rewhi","Tertiary","Fire","Icefire","Cyane","Light Pink","Autumn",
"Magenta","Magred","Yelmag","Yelblu","Orange & Teal","Tiamat","April Night","Orangery","C9","Sakura",
"Aurora","Atlantica","C9 2","C9 New","Temperature","Aurora 2"
]}


I have tried this on a couple of ESP8266 boards with the same result

I Have just tried Standard WLED version 12.0 & 12.1 on ESP8266 - same results as above

**Comment by thibmaek** [comment]
Hmmm I compared the two JSON outputs and found the following difference:
- `/json`: Outputs the correct state as JSON. This is merely a snapshot in time and would need to be manually set as state via JSON api to restore.
- `/json/cfg`: Reports the full configuration as JSON. This can be used to restore as backup

I'll check by flashing regular WLED 12.0 to an ESP8266 and see what it does when I send a GET request to `/json/cfg` and if it works there.

**Comment by thibmaek** [comment]
https://kno.wled.ge/features/presets/#new-version-011 the cfg.json and presets.json should be available since 0.11.0 though

<blockquote><div><strong><a href="https://kno.wled.ge/features/presets/#new-version-011">Presets - WLED Project</a></strong></div></blockquote>

**Comment by christiansuryanto** [comment]
on file
 /cmd/export.go
 
 Must change / edit this lines :

 line 82, from
 url := fmt.Sprintf("http://%s/edit?download=cfg.json", host)
 to
 url := fmt.Sprintf("http://%s/edit?download=/cfg.json", host)
 
 line 88, from
 url := fmt.Sprintf("http://%s/edit?download=presets.json", host)
 to
 url := fmt.Sprintf("http://%s/edit?download=/presets.json", host)
 
 Then recompile the main.go to produce the binary (in windows  EXE file).
 
 The it works like a charm.

**Comment by thibmaek** [comment]
Thanks, tried that locally as well using a REST client and works like it should. Will release a new version shortly

**Comment by thibmaek** [comment]
Fixed in 52a1ab82ba6c0047be1ae02ced025f32eebc83f2 , released in v1.0.1
